### PR TITLE
Add nomaakip to team.html

### PR DESCRIPTION
**Pull request by Nomaakip**
can i add this greg

### CODE REVIEW

**Comment by 5quirre1** [comment]
Hey, We'll check this out. Could we plz put it in nightly before we put it into the official one ^^

**Comment by Nomaakip** [comment]
Will do

**Comment by wish13yt** [comment]
thought this was already added LMAO
will review

**Comment by wish13yt** [comment]
Improper pull request. Please do not use your own fork, instead create a new branch and make a pull request from there. ^-^

**Comment by wish13yt** [comment]
added manually in https://github.com/Freakybob-Team/Freakybob.site/commit/2d847178c9f973ac1b43062de988b4c9f369a651

**Pull request closed without merging**
